Flink:
  ports:
  - 8081:8081/tcp
  restart: always
  tty: true
  image: flink:latest
  stdin_open: true
  expose:
    - "6123"
  command: jobmanager
  environment:
    - JOB_MANAGER_RPC_ADDRESS=jobmanager

