.catalog:
  name: "Kibana"
  version: "1.1.1-rancher1"
  description: "Kibana: Explore & Visualize Your Data"
nginx-proxy:
  metadata:
    nginx:
      conf:
        servername: "kibana"
        upstream_port: 5601 
