.catalog:
  name: "Kibana"
  version: "6.3.0-rancher1"
  description: "Kibana: Explore & Visualize Your Data"
nifi-master:
  scale: 1
nginx-proxy:
  metadata:
    nginx:
      conf:
        servername: "nifi-master"
        upstream_port: 8081
